//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class StoriesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get all stories
     * @return OK
     */
    getStories(): Promise<StoryVm> {
        let url_ = this.baseUrl + "/api/Stories";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetStories(_response);
        });
    }

    protected processGetStories(response: Response): Promise<StoryVm> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StoryVm.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<StoryVm>(null as any);
    }

    /**
     * Create a new story
     * @return Created
     */
    createStory(body: CreateStoryCommand): Promise<number> {
        let url_ = this.baseUrl + "/api/Stories";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateStory(_response);
        });
    }

    protected processCreateStory(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result201 = resultData201 !== undefined ? resultData201 : null as any;
    
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    /**
     * Get Story by Id
     * @return OK
     */
    getStoryById(id: number): Promise<StoryDto> {
        let url_ = this.baseUrl + "/api/Stories/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetStoryById(_response);
        });
    }

    protected processGetStoryById(response: Response): Promise<StoryDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StoryDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<StoryDto>(null as any);
    }

    /**
     * Update a story
     * @return No Content
     */
    updateStory(id: number, body: UpdateStoryCommand): Promise<void> {
        let url_ = this.baseUrl + "/api/Stories/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateStory(_response);
        });
    }

    protected processUpdateStory(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Delete a story
     * @return No Content
     */
    deleteStory(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Stories/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteStory(_response);
        });
    }

    protected processDeleteStory(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class UsersClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Register
     * @return OK
     */
    register(body: RegisterRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/Users/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = HttpValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Log in
     * @return OK
     */
    login(body: LoginRequest): Promise<AccessTokenResponse> {
        let url_ = this.baseUrl + "/api/Users/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<AccessTokenResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AccessTokenResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccessTokenResponse>(null as any);
    }

    /**
     * Refresh token
     * @return OK
     */
    refresh(body: RefreshRequest): Promise<AccessTokenResponse> {
        let url_ = this.baseUrl + "/api/Users/refresh";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRefresh(_response);
        });
    }

    protected processRefresh(response: Response): Promise<AccessTokenResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AccessTokenResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccessTokenResponse>(null as any);
    }

    /**
     * Get account info
     * @return OK
     */
    getInfo(): Promise<InfoResponse> {
        let url_ = this.baseUrl + "/api/Users/manage/info";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetInfo(_response);
        });
    }

    protected processGetInfo(response: Response): Promise<InfoResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = InfoResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<InfoResponse>(null as any);
    }

    /**
     * Log out
     * @param body (optional) 
     * @return OK
     */
    logout(body: any | null | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Users/logout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AccessTokenResponse implements IAccessTokenResponse {
    tokenType!: string;
    accessToken!: string;
    expiresIn!: number;
    refreshToken!: string;

    [key: string]: any;

    constructor(data?: IAccessTokenResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.tokenType = _data["tokenType"];
            this.accessToken = _data["accessToken"];
            this.expiresIn = _data["expiresIn"];
            this.refreshToken = _data["refreshToken"];
        }
    }

    static fromJS(data: any): AccessTokenResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AccessTokenResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["tokenType"] = this.tokenType;
        data["accessToken"] = this.accessToken;
        data["expiresIn"] = this.expiresIn;
        data["refreshToken"] = this.refreshToken;
        return data;
    }
}

export interface IAccessTokenResponse {
    tokenType: string;
    accessToken: string;
    expiresIn: number;
    refreshToken: string;

    [key: string]: any;
}

export class CreateStoryCommand implements ICreateStoryCommand {
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    imageUrl?: string | undefined;
    totalChapters?: number | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;

    constructor(data?: ICreateStoryCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.title = _data["title"];
            this.titleRaw = _data["titleRaw"];
            this.storyWebId = _data["storyWebId"];
            this.linkRaw = _data["linkRaw"];
            this.author = _data["author"];
            this.imageUrl = _data["imageUrl"];
            this.totalChapters = _data["totalChapters"];
            this.descriptionRaw = _data["descriptionRaw"];
            this.descriptionEdit = _data["descriptionEdit"];
            this.linkChapterOne = _data["linkChapterOne"];
            if (Array.isArray(_data["genres"])) {
                this.genres = [] as any;
                for (let item of _data["genres"])
                    this.genres!.push(item);
            }
            this.isScraped = _data["isScraped"];
            this.isEdited = _data["isEdited"];
            this.isComment = _data["isComment"];
            this.publish = _data["publish"];
            this.uploaded = _data["uploaded"];
            this.isFull = _data["isFull"];
            this.earnCount = _data["earnCount"];
            this.earnNow = _data["earnNow"];
            this.adCount = _data["adCount"];
            this.paid = _data["paid"];
            this.isEarning = _data["isEarning"];
        }
    }

    static fromJS(data: any): CreateStoryCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateStoryCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["title"] = this.title;
        data["titleRaw"] = this.titleRaw;
        data["storyWebId"] = this.storyWebId;
        data["linkRaw"] = this.linkRaw;
        data["author"] = this.author;
        data["imageUrl"] = this.imageUrl;
        data["totalChapters"] = this.totalChapters;
        data["descriptionRaw"] = this.descriptionRaw;
        data["descriptionEdit"] = this.descriptionEdit;
        data["linkChapterOne"] = this.linkChapterOne;
        if (Array.isArray(this.genres)) {
            data["genres"] = [];
            for (let item of this.genres)
                data["genres"].push(item);
        }
        data["isScraped"] = this.isScraped;
        data["isEdited"] = this.isEdited;
        data["isComment"] = this.isComment;
        data["publish"] = this.publish;
        data["uploaded"] = this.uploaded;
        data["isFull"] = this.isFull;
        data["earnCount"] = this.earnCount;
        data["earnNow"] = this.earnNow;
        data["adCount"] = this.adCount;
        data["paid"] = this.paid;
        data["isEarning"] = this.isEarning;
        return data;
    }
}

export interface ICreateStoryCommand {
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    imageUrl?: string | undefined;
    totalChapters?: number | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;
}

export class HttpValidationProblemDetails implements IHttpValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; };

    [key: string]: any;

    constructor(data?: IHttpValidationProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
            if (_data["errors"]) {
                this.errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (this.errors as any)![key] = _data["errors"][key] !== undefined ? _data["errors"][key] : [];
                }
            }
        }
    }

    static fromJS(data: any): HttpValidationProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new HttpValidationProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    (data["errors"] as any)[key] = (this.errors as any)[key];
            }
        }
        return data;
    }
}

export interface IHttpValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; };

    [key: string]: any;
}

export class InfoResponse implements IInfoResponse {
    email!: string;
    isEmailConfirmed!: boolean;

    [key: string]: any;

    constructor(data?: IInfoResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.isEmailConfirmed = _data["isEmailConfirmed"];
        }
    }

    static fromJS(data: any): InfoResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InfoResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["isEmailConfirmed"] = this.isEmailConfirmed;
        return data;
    }
}

export interface IInfoResponse {
    email: string;
    isEmailConfirmed: boolean;

    [key: string]: any;
}

export class LoginRequest implements ILoginRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class RefreshRequest implements IRefreshRequest {
    refreshToken!: string;

    [key: string]: any;

    constructor(data?: IRefreshRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.refreshToken = _data["refreshToken"];
        }
    }

    static fromJS(data: any): RefreshRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RefreshRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["refreshToken"] = this.refreshToken;
        return data;
    }
}

export interface IRefreshRequest {
    refreshToken: string;

    [key: string]: any;
}

export class RegisterRequest implements IRegisterRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: IRegisterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): RegisterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface IRegisterRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class StoryDto implements IStoryDto {
    id?: number;
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    imageUrl?: string | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;

    constructor(data?: IStoryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.title = _data["title"];
            this.titleRaw = _data["titleRaw"];
            this.storyWebId = _data["storyWebId"];
            this.linkRaw = _data["linkRaw"];
            this.author = _data["author"];
            this.imageUrl = _data["imageUrl"];
            this.descriptionRaw = _data["descriptionRaw"];
            this.descriptionEdit = _data["descriptionEdit"];
            this.linkChapterOne = _data["linkChapterOne"];
            if (Array.isArray(_data["genres"])) {
                this.genres = [] as any;
                for (let item of _data["genres"])
                    this.genres!.push(item);
            }
            this.isScraped = _data["isScraped"];
            this.isEdited = _data["isEdited"];
            this.isComment = _data["isComment"];
            this.publish = _data["publish"];
            this.uploaded = _data["uploaded"];
            this.isFull = _data["isFull"];
            this.earnCount = _data["earnCount"];
            this.earnNow = _data["earnNow"];
            this.adCount = _data["adCount"];
            this.paid = _data["paid"];
            this.isEarning = _data["isEarning"];
        }
    }

    static fromJS(data: any): StoryDto {
        data = typeof data === 'object' ? data : {};
        let result = new StoryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["title"] = this.title;
        data["titleRaw"] = this.titleRaw;
        data["storyWebId"] = this.storyWebId;
        data["linkRaw"] = this.linkRaw;
        data["author"] = this.author;
        data["imageUrl"] = this.imageUrl;
        data["descriptionRaw"] = this.descriptionRaw;
        data["descriptionEdit"] = this.descriptionEdit;
        data["linkChapterOne"] = this.linkChapterOne;
        if (Array.isArray(this.genres)) {
            data["genres"] = [];
            for (let item of this.genres)
                data["genres"].push(item);
        }
        data["isScraped"] = this.isScraped;
        data["isEdited"] = this.isEdited;
        data["isComment"] = this.isComment;
        data["publish"] = this.publish;
        data["uploaded"] = this.uploaded;
        data["isFull"] = this.isFull;
        data["earnCount"] = this.earnCount;
        data["earnNow"] = this.earnNow;
        data["adCount"] = this.adCount;
        data["paid"] = this.paid;
        data["isEarning"] = this.isEarning;
        return data;
    }
}

export interface IStoryDto {
    id?: number;
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    imageUrl?: string | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;
}

export class StoryVm implements IStoryVm {
    stories?: StoryDto[];

    [key: string]: any;

    constructor(data?: IStoryVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["stories"])) {
                this.stories = [] as any;
                for (let item of _data["stories"])
                    this.stories!.push(StoryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): StoryVm {
        data = typeof data === 'object' ? data : {};
        let result = new StoryVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.stories)) {
            data["stories"] = [];
            for (let item of this.stories)
                data["stories"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IStoryVm {
    stories?: StoryDto[];

    [key: string]: any;
}

export class UpdateStoryCommand implements IUpdateStoryCommand {
    id?: number;
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    totalChapters?: number | undefined;
    imageUrl?: string | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;

    constructor(data?: IUpdateStoryCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.title = _data["title"];
            this.titleRaw = _data["titleRaw"];
            this.storyWebId = _data["storyWebId"];
            this.linkRaw = _data["linkRaw"];
            this.author = _data["author"];
            this.totalChapters = _data["totalChapters"];
            this.imageUrl = _data["imageUrl"];
            this.descriptionRaw = _data["descriptionRaw"];
            this.descriptionEdit = _data["descriptionEdit"];
            this.linkChapterOne = _data["linkChapterOne"];
            if (Array.isArray(_data["genres"])) {
                this.genres = [] as any;
                for (let item of _data["genres"])
                    this.genres!.push(item);
            }
            this.isScraped = _data["isScraped"];
            this.isEdited = _data["isEdited"];
            this.isComment = _data["isComment"];
            this.publish = _data["publish"];
            this.uploaded = _data["uploaded"];
            this.isFull = _data["isFull"];
            this.earnCount = _data["earnCount"];
            this.earnNow = _data["earnNow"];
            this.adCount = _data["adCount"];
            this.paid = _data["paid"];
            this.isEarning = _data["isEarning"];
        }
    }

    static fromJS(data: any): UpdateStoryCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateStoryCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["title"] = this.title;
        data["titleRaw"] = this.titleRaw;
        data["storyWebId"] = this.storyWebId;
        data["linkRaw"] = this.linkRaw;
        data["author"] = this.author;
        data["totalChapters"] = this.totalChapters;
        data["imageUrl"] = this.imageUrl;
        data["descriptionRaw"] = this.descriptionRaw;
        data["descriptionEdit"] = this.descriptionEdit;
        data["linkChapterOne"] = this.linkChapterOne;
        if (Array.isArray(this.genres)) {
            data["genres"] = [];
            for (let item of this.genres)
                data["genres"].push(item);
        }
        data["isScraped"] = this.isScraped;
        data["isEdited"] = this.isEdited;
        data["isComment"] = this.isComment;
        data["publish"] = this.publish;
        data["uploaded"] = this.uploaded;
        data["isFull"] = this.isFull;
        data["earnCount"] = this.earnCount;
        data["earnNow"] = this.earnNow;
        data["adCount"] = this.adCount;
        data["paid"] = this.paid;
        data["isEarning"] = this.isEarning;
        return data;
    }
}

export interface IUpdateStoryCommand {
    id?: number;
    title?: string | undefined;
    titleRaw?: string | undefined;
    storyWebId?: string | undefined;
    linkRaw?: string | undefined;
    author?: string | undefined;
    totalChapters?: number | undefined;
    imageUrl?: string | undefined;
    descriptionRaw?: string | undefined;
    descriptionEdit?: string | undefined;
    linkChapterOne?: string | undefined;
    genres?: string[] | undefined;
    isScraped?: boolean;
    isEdited?: boolean;
    isComment?: boolean;
    publish?: number;
    uploaded?: number;
    isFull?: boolean;
    earnCount?: number;
    earnNow?: number;
    adCount?: number;
    paid?: number;
    isEarning?: boolean;

    [key: string]: any;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}